services:
  arangodb-data-01:
    image: arangodb:3.8.7
    container_name: arangodb-data-01
    restart: always
    environment:
      - ARANGO_RANDOM_ROOT_PASSWORD=1
    volumes:
      - '/path/to/conf/folder:/etc/arangodb'
      - '/path/to/apps/folder:/var/lib/arangodb3-apps'
      - '/path/to/folder/data/folder:/var/lib/arangodb3'
      - '/usr/share/zoneinfo/Asia/Jakarta:/etc/localtime'
    networks:
      - 'arangodb-cluster'
    ports:
      - "6001:8529"
    command: >
      arangod
      --server.jwt-secret-keyfile=/etc/arangodb/secret.jwt
      --server.endpoint tcp://0.0.0.0:8529
      --cluster.my-address tcp://your.ip.addr:6001
      --cluster.my-role DBSERVER
      --cluster.agency-endpoint tcp://your.ip.addr:5001
