version: '3.5'
services:
  arangodb-coordinator-01:
    image: arangodb:3.8.7
    container_name: arangodb-coordinator-01
    restart: always
    environment:
      - ARANGO_RANDOM_ROOT_PASSWORD=1
    volumes:
      - '/path/to/folder:/etc/arangodb'
      - '/path/to/folder:/var/lib/arangodb3-apps'
      - '/path/to/folder:/var/lib/arangodb3'
    networks:
      - 'arangodb'
    ports:
      - "8529:8529"
    command: >
      arangod
      --server.jwt-secret-keyfile=/etc/arangodb/secret.jwt
      --server.endpoint tcp://0.0.0.0:8529
      --cluster.my-address tcp://10.188.1.19:8529
      --cluster.my-role COORDINATOR
      --cluster.agency-endpoint tcp://10.188.1.19:5001
      --cluster.default-replication-factor 3

networks:
  paper-arangodb:
    driver: bridge
    name: arangodb
