services:
  arangodb-coordinator-01:
    image: arangodb:3.8.7
    container_name: arangodb-coordinator-01
    restart: always
    environment:
      - ARANGO_RANDOM_ROOT_PASSWORD=1
    volumes:
      - '/path/to/conf/folder:/etc/arangodb'
      - '/path/to/apps/folder:/var/lib/arangodb3-apps'
      - '/path/to/folder/data/folder:/var/lib/arangodb3'
    networks:
      - 'arangodb-cluster'
    ports:
      - "8529:8529"
    command: >
      arangod
      --server.jwt-secret-keyfile=/etc/arangodb/secret.jwt
      --server.endpoint tcp://0.0.0.0:8529
      --cluster.my-address tcp://your.ip.addr:8529
      --cluster.my-role COORDINATOR
      --cluster.agency-endpoint tcp://your.ip.addr:5001
      --cluster.system-replication-factor 1
